// <auto-generated />

namespace In.ProjectEKA.HipService.Discovery.Database.Migrations
{
    using System;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

    [DbContext(typeof(DiscoveryContext))]
    internal class DiscoveryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("In.ProjectEKA.HipService.Discovery.Model.DiscoveryRequest", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy",
                        NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("ConsentManagerUserId")
                    .IsRequired()
                    .HasColumnType("character varying(50)")
                    .HasMaxLength(50);

                b.Property<string>("PatientReferenceNumber")
                    .IsRequired()
                    .HasColumnType("character varying(50)")
                    .HasMaxLength(50);

                b.Property<DateTime>("Timestamp")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp without time zone")
                    .HasDefaultValueSql("now()");

                b.Property<string>("TransactionId")
                    .IsRequired()
                    .HasColumnType("character varying(50)")
                    .HasMaxLength(50);

                b.HasKey("Id");

                b.HasIndex("TransactionId")
                    .IsUnique();

                b.ToTable("DiscoveryRequest");
            });
#pragma warning restore 612, 618
        }
    }
}